### ISSUE TITLE
calibrate_screen.py - 'tuple' object has no attribute 'sort'

### ISSUE THREAD

**Issue by mrvnklm** [dinvlad/HyperVision#3]
After running `calibrate_camera.py` successfully, the `calibrate_screen.py` always returns the error ` 'tuple' object has no attribute 'sort'`. The screen is withing the cameras view, the lights are off, the screen is bright and visible within the preview window.
I just noticed, that the blue rectangles are missing after the white screen appears for like a second.

Do you have any idea what could be the issue?

**Comment by dinvlad** [comment]
Sorry not sure tbh, I haven't seen that before. If you could share the JSON file that it saved, that would be helpful - I think it might've saved something incorrectly.

**Comment by mrvnklm** [comment]
I just figured out, that it was an issue with a newer version of opencv-python. I had to install python 3.9 and use opencv-python==4.5.3.56 to make it work.
